'use client';
/**
 * LanguageContext.tsx - ระบบภาษา 10 ภาษา (Multi-Language Support)
 * คีเวิร์ดการเงินยังเป็นภาษาอังกฤษ คำทั่วไปแปล
 */

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// รายการภาษาที่รองรับ (10 ภาษา)
export const languages = [
    { code: 'th', flag: '🇹🇭', name: 'ไทย' },
    { code: 'en', flag: '🇺🇸', name: 'English' },
    { code: 'zh', flag: '🇨🇳', name: '中文' },
    { code: 'es', flag: '🇪🇸', name: 'Español' },
    { code: 'hi', flag: '🇮🇳', name: 'हिन्दी' },
    { code: 'ar', flag: '🇸🇦', name: 'العربية' },
    { code: 'pt', flag: '🇧🇷', name: 'Português' },
    { code: 'fr', flag: '🇫🇷', name: 'Français' },
    { code: 'ru', flag: '🇷🇺', name: 'Русский' },
    { code: 'ja', flag: '🇯🇵', name: '日本語' }
] as const;

export type LangCode = typeof languages[number]['code'];

// Dictionary ทุกภาษา (ภาษาไทยใช้ Keywords อังกฤษผสม)
const dictionary: Record<LangCode, Record<string, string>> = {
    th: {
        // Navbar
        login: 'เข้าสู่ระบบ',
        register: 'สมัคร',
        logout: 'ออก',
        dashboard: 'ประวัติ',
        // Hero
        heroTitle: 'เทรด Smarter ไม่ใช่ Harder',
        heroSubtitle: 'เครื่องมือคำนวณ Position Size ระดับมืออาชีพ',
        welcome: 'สวัสดี',
        readyToTrade: 'พร้อมเทรดแล้ว!',
        // Calculator
        positionCalc: 'Position Calculator',
        calcDesc: 'คำนวณ Multi-TP/SL พร้อม AI Score',
        tradingPair: 'คู่เทรด',
        direction: 'ทิศทาง',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Margin ที่ต้องวาง',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'บันทึก',
        saving: 'กำลังบันทึก...',
        // Features
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'คำนวณขนาดไม้ที่เหมาะสม',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'บันทึกและติดตามประวัติ',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'คะแนนประเมิน Setup',
        // CTA
        unlockFeatures: 'ปลดล็อค Full Features',
        ctaDesc: 'Login เพื่อบันทึกและวิเคราะห์',
        start: 'เริ่มต้นใช้งาน',
        // Dashboard
        tradeHistory: 'ประวัติการเทรด',
        quickActions: 'Quick Actions',
        viewHistory: 'ดูประวัติ',
        exchange: 'Exchange',
        entryReason: 'เหตุผลการเข้า',
        // Validation
        pleaseLogin: 'กรุณาเข้าสู่ระบบก่อน',
        fillAllFields: 'กรอกข้อมูลให้ครบ',
        savedSuccess: 'บันทึกสำเร็จ!',
        // Footer
        footer: 'หาที่ฝึกงาน | ปี 4 | MathCom',
    },
    en: {
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        dashboard: 'History',
        heroTitle: 'Trade Smarter, Not Harder',
        heroSubtitle: 'Professional Position Size Calculator',
        welcome: 'Hello',
        readyToTrade: 'Ready to trade!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL with AI Score',
        tradingPair: 'Trading Pair',
        direction: 'Direction',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'Save',
        saving: 'Saving...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calculate optimal position size',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Track all your trades',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Setup evaluation and alerts',
        unlockFeatures: 'Unlock Full Features',
        ctaDesc: 'Login to save and analyze',
        start: 'Get Started',
        tradeHistory: 'Trade History',
        quickActions: 'Quick Actions',
        viewHistory: 'View History',
        exchange: 'Exchange',
        entryReason: 'Entry Reason',
        pleaseLogin: 'Please login first',
        fillAllFields: 'Fill all fields',
        savedSuccess: 'Saved successfully!',
        footer: 'Looking for internship | Year 4 | MathCom',
    },
    zh: {
        login: '登录',
        register: '注册',
        logout: '退出',
        dashboard: '历史',
        heroTitle: '更智能的交易',
        heroSubtitle: '专业的仓位计算器',
        welcome: '你好',
        readyToTrade: '准备交易！',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: '交易对',
        direction: '方向',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: '保存',
        saving: '保存中...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: '计算最佳仓位',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: '记录交易历史',
        aiScore: 'AI Trade Score',
        aiScoreDesc: '设置评估',
        unlockFeatures: '解锁全部功能',
        ctaDesc: '登录保存分析',
        start: '开始使用',
        tradeHistory: '交易历史',
        quickActions: '快捷操作',
        viewHistory: '查看历史',
        exchange: 'Exchange',
        entryReason: '入场理由',
        pleaseLogin: '请先登录',
        fillAllFields: '填写所有字段',
        savedSuccess: '保存成功！',
        footer: '寻找实习 | 大四',
    },
    es: {
        login: 'Iniciar',
        register: 'Registro',
        logout: 'Salir',
        dashboard: 'Historial',
        heroTitle: 'Opera más inteligente',
        heroSubtitle: 'Calculadora profesional',
        welcome: 'Hola',
        readyToTrade: '¡Listo!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Par',
        direction: 'Dirección',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'Guardar',
        saving: 'Guardando...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calcula posición óptima',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Historial de operaciones',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Evaluación de setup',
        unlockFeatures: 'Desbloquear',
        ctaDesc: 'Inicia sesión',
        start: 'Comenzar',
        tradeHistory: 'Historial',
        quickActions: 'Acciones',
        viewHistory: 'Ver',
        exchange: 'Exchange',
        entryReason: 'Razón',
        pleaseLogin: 'Inicia sesión',
        fillAllFields: 'Completa todo',
        savedSuccess: '¡Guardado!',
        footer: 'Buscando pasantía',
    },
    hi: {
        login: 'लॉगिन',
        register: 'पंजीकरण',
        logout: 'बाहर',
        dashboard: 'इतिहास',
        heroTitle: 'स्मार्ट ट्रेड करें',
        heroSubtitle: 'प्रोफेशनल कैलकुलेटर',
        welcome: 'नमस्ते',
        readyToTrade: 'तैयार!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'पेयर',
        direction: 'दिशा',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'सेव',
        saving: 'सेव हो रहा...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'सही पोजीशन साइज',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'ट्रेड इतिहास',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'सेटअप मूल्यांकन',
        unlockFeatures: 'अनलॉक करें',
        ctaDesc: 'लॉगिन करें',
        start: 'शुरू करें',
        tradeHistory: 'इतिहास',
        quickActions: 'त्वरित',
        viewHistory: 'देखें',
        exchange: 'Exchange',
        entryReason: 'कारण',
        pleaseLogin: 'लॉगिन करें',
        fillAllFields: 'सब भरें',
        savedSuccess: 'सेव हो गया!',
        footer: 'इंटर्नशिप खोज रहा',
    },
    ar: {
        login: 'دخول',
        register: 'تسجيل',
        logout: 'خروج',
        dashboard: 'التاريخ',
        heroTitle: 'تداول بذكاء',
        heroSubtitle: 'حاسبة احترافية',
        welcome: 'مرحبا',
        readyToTrade: 'جاهز!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'زوج',
        direction: 'اتجاه',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'حفظ',
        saving: 'جاري الحفظ...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'حساب الحجم',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'تتبع التداول',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'تقييم الإعداد',
        unlockFeatures: 'فتح الميزات',
        ctaDesc: 'سجل دخول',
        start: 'ابدأ',
        tradeHistory: 'التاريخ',
        quickActions: 'سريع',
        viewHistory: 'عرض',
        exchange: 'Exchange',
        entryReason: 'السبب',
        pleaseLogin: 'سجل دخول أولا',
        fillAllFields: 'املأ الكل',
        savedSuccess: 'تم الحفظ!',
        footer: 'أبحث عن تدريب',
    },
    pt: {
        login: 'Entrar',
        register: 'Registro',
        logout: 'Sair',
        dashboard: 'Histórico',
        heroTitle: 'Negocie com inteligência',
        heroSubtitle: 'Calculadora profissional',
        welcome: 'Olá',
        readyToTrade: 'Pronto!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Par',
        direction: 'Direção',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'Salvar',
        saving: 'Salvando...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calcule posição ideal',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Acompanhe trades',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Avaliação de setup',
        unlockFeatures: 'Desbloquear',
        ctaDesc: 'Faça login',
        start: 'Começar',
        tradeHistory: 'Histórico',
        quickActions: 'Ações',
        viewHistory: 'Ver',
        exchange: 'Exchange',
        entryReason: 'Motivo',
        pleaseLogin: 'Faça login',
        fillAllFields: 'Preencha tudo',
        savedSuccess: 'Salvo!',
        footer: 'Procurando estágio',
    },
    fr: {
        login: 'Connexion',
        register: 'Inscription',
        logout: 'Déconnexion',
        dashboard: 'Historique',
        heroTitle: 'Tradez intelligemment',
        heroSubtitle: 'Calculatrice professionnelle',
        welcome: 'Bonjour',
        readyToTrade: 'Prêt!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Paire',
        direction: 'Direction',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'Sauver',
        saving: 'Sauvegarde...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calculez position',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Suivez vos trades',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Évaluation du setup',
        unlockFeatures: 'Débloquer',
        ctaDesc: 'Connectez-vous',
        start: 'Commencer',
        tradeHistory: 'Historique',
        quickActions: 'Actions',
        viewHistory: 'Voir',
        exchange: 'Exchange',
        entryReason: 'Raison',
        pleaseLogin: 'Connectez-vous',
        fillAllFields: 'Remplir tout',
        savedSuccess: 'Sauvegardé!',
        footer: 'Recherche stage',
    },
    ru: {
        login: 'Вход',
        register: 'Регистрация',
        logout: 'Выход',
        dashboard: 'История',
        heroTitle: 'Торгуй умнее',
        heroSubtitle: 'Профессиональный калькулятор',
        welcome: 'Привет',
        readyToTrade: 'Готов!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Пара',
        direction: 'Направление',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: 'Сохранить',
        saving: 'Сохранение...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Расчет позиции',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'История сделок',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Оценка сетапа',
        unlockFeatures: 'Разблокировать',
        ctaDesc: 'Войдите',
        start: 'Начать',
        tradeHistory: 'История',
        quickActions: 'Действия',
        viewHistory: 'Смотреть',
        exchange: 'Exchange',
        entryReason: 'Причина',
        pleaseLogin: 'Войдите',
        fillAllFields: 'Заполните все',
        savedSuccess: 'Сохранено!',
        footer: 'Ищу стажировку',
    },
    ja: {
        login: 'ログイン',
        register: '登録',
        logout: 'ログアウト',
        dashboard: '履歴',
        heroTitle: 'スマートに取引',
        heroSubtitle: 'プロ用計算機',
        welcome: 'こんにちは',
        readyToTrade: '準備完了!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'ペア',
        direction: '方向',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        leverage: 'Leverage',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        save: '保存',
        saving: '保存中...',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: '最適なサイズ計算',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: '取引履歴追跡',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'セットアップ評価',
        unlockFeatures: 'ロック解除',
        ctaDesc: 'ログインして',
        start: '始める',
        tradeHistory: '履歴',
        quickActions: 'クイック',
        viewHistory: '見る',
        exchange: 'Exchange',
        entryReason: '理由',
        pleaseLogin: 'ログインして',
        fillAllFields: '全て記入',
        savedSuccess: '保存完了!',
        footer: 'インターンシップ探し中',
    },
};

// Context Type
interface LanguageContextType {
    lang: LangCode;
    setLang: (lang: LangCode) => void;
    t: (key: string) => string;
    flag: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider Component
export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLangState] = useState<LangCode>('th');

    // โหลดภาษาจาก localStorage (ถ้ามี)
    useEffect(() => {
        const saved = localStorage.getItem('lang') as LangCode;
        if (saved && languages.some(l => l.code === saved)) {
            setLangState(saved);
        }
    }, []);

    // บันทึกภาษาลง localStorage
    const setLang = (newLang: LangCode) => {
        setLangState(newLang);
        localStorage.setItem('lang', newLang);
    };

    // ฟังก์ชันแปลภาษา (คืนค่า key ถ้าไม่มีในพจนานุกรม)
    const t = (key: string): string => {
        return dictionary[lang][key] || dictionary['en'][key] || key;
    };

    // ธงชาติปัจจุบัน
    const flag = languages.find(l => l.code === lang)?.flag || '🇹🇭';

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, flag }}>
            {children}
        </LanguageContext.Provider>
    );
}

// Custom Hook
export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
