'use client';
/**
 * ===================================================================
 * LanguageContext.tsx - ระบบภาษา 10 ภาษา (Multi-Language Support)
 * ===================================================================
 * 📚 สร้างโดย: MMRRDiKub Team
 * 🎯 วัตถุประสงค์: รองรับหลายภาษาทั่วทั้งเว็บไซต์
 * 
 * 💡 หลักการ:
 *    - คีเวิร์ดการเงินสำคัญยังเป็นภาษาอังกฤษ (Position Size, Leverage, R:R)
 *    - คำทั่วไปแปลตามภาษาที่เลือก
 *    - บันทึกภาษาลง localStorage เพื่อจำไว้
 * 
 * 🔧 วิธีใช้:
 *    const { t, lang, setLang, flag } = useLanguage();
 *    <span>{t('login')}</span>  // แสดง "เข้าสู่ระบบ" หรือ "Login" ตามภาษา
 * ===================================================================
 */

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// === รายการภาษาที่รองรับ (10 ภาษา) ===
export const languages = [
    { code: 'th', flag: '🇹🇭', name: 'ไทย' },
    { code: 'en', flag: '🇺🇸', name: 'English' },
    { code: 'zh', flag: '🇨🇳', name: '中文' },
    { code: 'es', flag: '🇪🇸', name: 'Español' },
    { code: 'hi', flag: '🇮🇳', name: 'हिन्दी' },
    { code: 'ar', flag: '🇸🇦', name: 'العربية' },
    { code: 'pt', flag: '🇧🇷', name: 'Português' },
    { code: 'fr', flag: '🇫🇷', name: 'Français' },
    { code: 'ru', flag: '🇷🇺', name: 'Русский' },
    { code: 'ja', flag: '🇯🇵', name: '日本語' }
] as const;

export type LangCode = typeof languages[number]['code'];

/**
 * ===================================================================
 * 📖 Dictionary - พจนานุกรมแปลภาษา (ทุกข้อความในเว็บ)
 * ===================================================================
 * หมายเหตุ: คีเวิร์ดการเงินสำคัญ (Position Size, Leverage, R:R, TP, SL) 
 *          ยังคงเป็นอังกฤษในทุกภาษาเพื่อความเป็นมาตรฐานสากล
 */
const dictionary: Record<LangCode, Record<string, string>> = {
    // =====================================================================
    // 🇹🇭 ภาษาไทย - ใช้คีเวิร์ดอังกฤษผสมในบางคำที่เทรดเดอร์ไทยคุ้นเคย
    // =====================================================================
    th: {
        // === Navbar (แถบเมนูบน) ===
        login: 'เข้าสู่ระบบ',
        register: 'สมัคร',
        logout: 'ออก',
        dashboard: 'ประวัติ',

        // === Hero Section (หน้าแรก) ===
        heroTitle: 'เทรด Smarter ไม่ใช่ Harder',
        heroSubtitle: 'เครื่องมือคำนวณ Position Size ระดับมืออาชีพ',
        welcome: 'สวัสดี',
        readyToTrade: 'พร้อมเทรดแล้ว!',

        // === Calculator (เครื่องคิดเลข) ===
        positionCalc: 'Position Calculator',
        calcDesc: 'คำนวณ Multi-TP/SL พร้อม AI Score',
        tradingPair: 'คู่เทรด',
        searchPair: 'พิมพ์ค้นหา... BTC, AI, Meme, DeFi',
        searchHint: 'ค้นหาด้วย: ชื่อเหรียญ, หมวดหมู่ หรือ Keywords',
        addNewPair: 'เพิ่มคู่ใหม่',
        noPairFound: 'ไม่พบคู่เทรด - พิมพ์รูปแบบ XXX/USDT เพื่อเพิ่มใหม่',
        direction: 'ทิศทาง',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'ปลอดภัย',
        riskModerate: 'ปานกลาง',
        riskRisky: 'เสี่ยง',
        leverage: 'Leverage',
        levLow: 'ต่ำ',
        levMed: 'กลาง',
        levHigh: 'สูง',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'ต้องครบ 100%',
        add: 'เพิ่ม',
        remove: 'ลบ',

        // === Results (ผลลัพธ์) ===
        positionSize: 'Position Size',
        requiredMargin: 'Margin ที่ต้องวาง',
        quantity: 'จำนวน',
        riskAmount: 'ความเสี่ยง',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',

        // === AI Score ===
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'คะแนนประเมิน Setup',
        excellent: 'ยอดเยี่ยม!',
        good: 'ดี',
        moderate: 'พอใช้',
        risky: 'เสี่ยง',
        veryRisky: 'เสี่ยงมาก!',

        // === Buttons ===
        save: 'บันทึก',
        saving: 'กำลังบันทึก...',
        savedSuccess: 'บันทึกสำเร็จ!',
        viewDashboard: 'ดูประวัติ',
        continueTrading: 'เทรดต่อ',

        // === Entry Reason ===
        entryReason: 'เหตุผลการเข้า',
        selectReason: 'เลือกเหตุผล',
        customReason: 'เหตุผลอื่น...',

        // === Exchange ===
        exchange: 'Exchange',
        selectExchange: 'เลือก Exchange',

        // === Features Section ===
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'คำนวณขนาดไม้ที่เหมาะสม',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'บันทึกและติดตามประวัติ',

        // === CTA (Call to Action) ===
        unlockFeatures: 'ปลดล็อค Full Features',
        ctaDesc: 'Login เพื่อบันทึกและวิเคราะห์',
        start: 'เริ่มต้นใช้งาน',

        // === Dashboard ===
        tradeHistory: 'ประวัติการเทรด',
        quickActions: 'Quick Actions',
        viewHistory: 'ดูประวัติ',
        totalTrades: 'เทรดทั้งหมด',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'เทรดเปิด',
        noTrades: 'ยังไม่มีประวัติเทรด',
        startTrading: 'เริ่มเทรดเลย!',

        // === Trade Status ===
        statusOpen: 'เปิดอยู่',
        statusWin: 'ชนะ',
        statusLoss: 'แพ้',
        endOrder: 'จบออเดอร์',
        markWin: 'บันทึก WIN',
        markLoss: 'บันทึก LOSS',

        // === Validation & Errors ===
        pleaseLogin: 'กรุณาเข้าสู่ระบบก่อน',
        fillAllFields: 'กรุณากรอกข้อมูลให้ครบ',
        invalidPair: 'คู่เทรดต้องเป็นรูปแบบ XXX/USDT',
        tokenExpired: 'Token หมดอายุ - กรุณา Login ใหม่',
        serverError: 'เกิดข้อผิดพลาด',
        cannotSave: 'ไม่สามารถบันทึกได้',

        // === Footer ===
        footer: 'หาที่ฝึกงาน | ปี 4 | MathCom',
        madeWith: 'สร้างด้วย',

        // === Login/Register ===
        welcomeBack: 'ยินดีต้อนรับกลับมา!',
        createAccount: 'สร้างบัญชีใหม่',
        noAccount: 'ยังไม่มีบัญชี?',
        haveAccount: 'มีบัญชีอยู่แล้ว?',
        back: 'กลับ',
        username: 'ชื่อผู้ใช้',
        password: 'รหัสผ่าน',
        confirmPassword: 'ยืนยันรหัสผ่าน',
        email: 'อีเมล',
        passwordMismatch: 'รหัสผ่านไม่ตรงกัน',
        registering: 'กำลังสมัคร...',
        loggingIn: 'กำลังเข้าสู่ระบบ...',
        registerSuccess: 'สมัครสำเร็จ!',
    },

    // =====================================================================
    // 🇺🇸 English
    // =====================================================================
    en: {
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        dashboard: 'History',
        heroTitle: 'Trade Smarter, Not Harder',
        heroSubtitle: 'Professional Position Size Calculator',
        welcome: 'Hello',
        readyToTrade: 'Ready to trade!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL with AI Score',
        tradingPair: 'Trading Pair',
        searchPair: 'Search... BTC, AI, Meme, DeFi',
        searchHint: 'Search by: coin name, category, or keywords',
        addNewPair: 'Add new pair',
        noPairFound: 'No pair found - type XXX/USDT to add',
        direction: 'Direction',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'Safe',
        riskModerate: 'Moderate',
        riskRisky: 'Risky',
        leverage: 'Leverage',
        levLow: 'Low',
        levMed: 'Med',
        levHigh: 'High',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'Must be 100%',
        add: 'Add',
        remove: 'Remove',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'Quantity',
        riskAmount: 'Risk Amount',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Setup evaluation',
        excellent: 'Excellent!',
        good: 'Good',
        moderate: 'Moderate',
        risky: 'Risky',
        veryRisky: 'Very Risky!',
        save: 'Save',
        saving: 'Saving...',
        savedSuccess: 'Saved!',
        viewDashboard: 'View History',
        continueTrading: 'Continue',
        entryReason: 'Entry Reason',
        selectReason: 'Select reason',
        customReason: 'Other...',
        exchange: 'Exchange',
        selectExchange: 'Select Exchange',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calculate optimal size',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Track all trades',
        unlockFeatures: 'Unlock Features',
        ctaDesc: 'Login to save and analyze',
        start: 'Get Started',
        tradeHistory: 'Trade History',
        quickActions: 'Quick Actions',
        viewHistory: 'View History',
        totalTrades: 'Total Trades',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'Open Trades',
        noTrades: 'No trades yet',
        startTrading: 'Start trading!',
        statusOpen: 'Open',
        statusWin: 'Win',
        statusLoss: 'Loss',
        endOrder: 'End Order',
        markWin: 'Mark WIN',
        markLoss: 'Mark LOSS',
        pleaseLogin: 'Please login first',
        fillAllFields: 'Fill all fields',
        invalidPair: 'Pair must be XXX/USDT format',
        tokenExpired: 'Token expired - Please login again',
        serverError: 'Server error',
        cannotSave: 'Cannot save',
        footer: 'Internship | Year 4 | MathCom',
        madeWith: 'Made with',
        welcomeBack: 'Welcome back!',
        createAccount: 'Create account',
        noAccount: 'No account?',
        haveAccount: 'Have account?',
        back: 'Back',
        username: 'Username',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        email: 'Email',
        passwordMismatch: 'Passwords do not match',
        registering: 'Registering...',
        loggingIn: 'Logging in...',
        registerSuccess: 'Registered!',
    },

    // =====================================================================
    // 🇨🇳 Chinese (Simplified)
    // =====================================================================
    zh: {
        login: '登录',
        register: '注册',
        logout: '退出',
        dashboard: '历史',
        heroTitle: '更智能地交易',
        heroSubtitle: '专业的仓位计算器',
        welcome: '你好',
        readyToTrade: '准备交易！',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: '交易对',
        searchPair: '搜索... BTC, AI, Meme',
        searchHint: '按币名、类别或关键词搜索',
        addNewPair: '添加新交易对',
        noPairFound: '未找到 - 输入 XXX/USDT 添加',
        direction: '方向',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: '安全',
        riskModerate: '中等',
        riskRisky: '风险',
        leverage: 'Leverage',
        levLow: '低',
        levMed: '中',
        levHigh: '高',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: '必须100%',
        add: '添加',
        remove: '删除',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: '数量',
        riskAmount: '风险金额',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: '设置评估',
        excellent: '优秀!',
        good: '好',
        moderate: '一般',
        risky: '风险',
        veryRisky: '高风险!',
        save: '保存',
        saving: '保存中...',
        savedSuccess: '保存成功!',
        viewDashboard: '查看历史',
        continueTrading: '继续',
        entryReason: '入场理由',
        selectReason: '选择理由',
        customReason: '其他...',
        exchange: 'Exchange',
        selectExchange: '选择交易所',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: '计算最佳仓位',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: '记录交易历史',
        unlockFeatures: '解锁功能',
        ctaDesc: '登录保存分析',
        start: '开始使用',
        tradeHistory: '交易历史',
        quickActions: '快捷操作',
        viewHistory: '查看历史',
        totalTrades: '总交易',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: '持仓',
        noTrades: '暂无交易',
        startTrading: '开始交易!',
        statusOpen: '持仓中',
        statusWin: '盈利',
        statusLoss: '亏损',
        endOrder: '结束订单',
        markWin: '盈利',
        markLoss: '亏损',
        pleaseLogin: '请先登录',
        fillAllFields: '填写所有字段',
        invalidPair: '格式须为 XXX/USDT',
        tokenExpired: 'Token过期 - 请重新登录',
        serverError: '服务器错误',
        cannotSave: '无法保存',
        footer: '寻找实习 | 大四',
        madeWith: '制作',
        welcomeBack: '欢迎回来!',
        createAccount: '创建账户',
        noAccount: '没有账户?',
        haveAccount: '已有账户?',
        back: '返回',
        username: '用户名',
        password: '密码',
        confirmPassword: '确认密码',
        email: '邮箱',
        passwordMismatch: '密码不匹配',
        registering: '注册中...',
        loggingIn: '登录中...',
        registerSuccess: '注册成功!',
    },

    // =====================================================================
    // 🇪🇸 Spanish
    // =====================================================================
    es: {
        login: 'Entrar',
        register: 'Registro',
        logout: 'Salir',
        dashboard: 'Historial',
        heroTitle: 'Opera más inteligente',
        heroSubtitle: 'Calculadora profesional',
        welcome: 'Hola',
        readyToTrade: '¡Listo!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Par',
        searchPair: 'Buscar... BTC, AI, Meme',
        searchHint: 'Buscar por nombre, categoría',
        addNewPair: 'Añadir nuevo',
        noPairFound: 'No encontrado',
        direction: 'Dirección',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'Seguro',
        riskModerate: 'Moderado',
        riskRisky: 'Riesgoso',
        leverage: 'Leverage',
        levLow: 'Bajo',
        levMed: 'Medio',
        levHigh: 'Alto',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'Debe ser 100%',
        add: 'Añadir',
        remove: 'Quitar',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'Cantidad',
        riskAmount: 'Cantidad Riesgo',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Evaluación',
        excellent: '¡Excelente!',
        good: 'Bueno',
        moderate: 'Moderado',
        risky: 'Riesgoso',
        veryRisky: '¡Muy Riesgoso!',
        save: 'Guardar',
        saving: 'Guardando...',
        savedSuccess: '¡Guardado!',
        viewDashboard: 'Ver Historial',
        continueTrading: 'Continuar',
        entryReason: 'Razón',
        selectReason: 'Seleccionar',
        customReason: 'Otro...',
        exchange: 'Exchange',
        selectExchange: 'Seleccionar',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calcula posición óptima',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Historial operaciones',
        unlockFeatures: 'Desbloquear',
        ctaDesc: 'Inicia sesión',
        start: 'Comenzar',
        tradeHistory: 'Historial',
        quickActions: 'Acciones',
        viewHistory: 'Ver',
        totalTrades: 'Total',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'Abiertos',
        noTrades: 'Sin historial',
        startTrading: '¡Empezar!',
        statusOpen: 'Abierto',
        statusWin: 'Ganado',
        statusLoss: 'Perdido',
        endOrder: 'Cerrar',
        markWin: 'WIN',
        markLoss: 'LOSS',
        pleaseLogin: 'Inicia sesión',
        fillAllFields: 'Completa todo',
        invalidPair: 'Formato XXX/USDT',
        tokenExpired: 'Token expirado',
        serverError: 'Error servidor',
        cannotSave: 'No guardado',
        footer: 'Buscando pasantía',
        madeWith: 'Hecho con',
        welcomeBack: '¡Bienvenido!',
        createAccount: 'Crear cuenta',
        noAccount: '¿Sin cuenta?',
        haveAccount: '¿Ya tienes?',
        back: 'Volver',
        username: 'Usuario',
        password: 'Contraseña',
        confirmPassword: 'Confirmar',
        email: 'Email',
        passwordMismatch: 'No coinciden',
        registering: 'Registrando...',
        loggingIn: 'Entrando...',
        registerSuccess: '¡Registrado!',
    },

    // =====================================================================
    // 🇮🇳 Hindi
    // =====================================================================
    hi: {
        login: 'लॉगिन',
        register: 'पंजीकरण',
        logout: 'बाहर',
        dashboard: 'इतिहास',
        heroTitle: 'स्मार्ट ट्रेड करें',
        heroSubtitle: 'प्रोफेशनल कैलकुलेटर',
        welcome: 'नमस्ते',
        readyToTrade: 'तैयार!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'पेयर',
        searchPair: 'खोजें... BTC, AI',
        searchHint: 'नाम या श्रेणी से खोजें',
        addNewPair: 'नया जोड़ें',
        noPairFound: 'नहीं मिला',
        direction: 'दिशा',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'सुरक्षित',
        riskModerate: 'मध्यम',
        riskRisky: 'जोखिम',
        leverage: 'Leverage',
        levLow: 'कम',
        levMed: 'मध्यम',
        levHigh: 'उच्च',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: '100% होना चाहिए',
        add: 'जोड़ें',
        remove: 'हटाएं',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'मात्रा',
        riskAmount: 'जोखिम राशि',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'मूल्यांकन',
        excellent: 'बढ़िया!',
        good: 'अच्छा',
        moderate: 'ठीक',
        risky: 'जोखिम',
        veryRisky: 'बहुत जोखिम!',
        save: 'सेव',
        saving: 'सेव हो रहा...',
        savedSuccess: 'सेव हो गया!',
        viewDashboard: 'इतिहास देखें',
        continueTrading: 'जारी',
        entryReason: 'कारण',
        selectReason: 'चुनें',
        customReason: 'अन्य...',
        exchange: 'Exchange',
        selectExchange: 'चुनें',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'सही साइज',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'ट्रेड इतिहास',
        unlockFeatures: 'अनलॉक करें',
        ctaDesc: 'लॉगिन करें',
        start: 'शुरू करें',
        tradeHistory: 'इतिहास',
        quickActions: 'त्वरित',
        viewHistory: 'देखें',
        totalTrades: 'कुल',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'खुले',
        noTrades: 'कोई इतिहास नहीं',
        startTrading: 'शुरू करें!',
        statusOpen: 'खुला',
        statusWin: 'जीत',
        statusLoss: 'हार',
        endOrder: 'बंद करें',
        markWin: 'WIN',
        markLoss: 'LOSS',
        pleaseLogin: 'लॉगिन करें',
        fillAllFields: 'सब भरें',
        invalidPair: 'XXX/USDT प्रारूप',
        tokenExpired: 'Token समाप्त',
        serverError: 'सर्वर त्रुटि',
        cannotSave: 'सेव नहीं हुआ',
        footer: 'इंटर्नशिप खोज',
        madeWith: 'बनाया',
        welcomeBack: 'स्वागत!',
        createAccount: 'खाता बनाएं',
        noAccount: 'खाता नहीं?',
        haveAccount: 'खाता है?',
        back: 'वापस',
        username: 'यूज़र',
        password: 'पासवर्ड',
        confirmPassword: 'पुष्टि करें',
        email: 'ईमेल',
        passwordMismatch: 'मेल नहीं',
        registering: 'पंजीकरण...',
        loggingIn: 'प्रवेश...',
        registerSuccess: 'पंजीकृत!',
    },

    // =====================================================================
    // 🇸🇦 Arabic
    // =====================================================================
    ar: {
        login: 'دخول',
        register: 'تسجيل',
        logout: 'خروج',
        dashboard: 'التاريخ',
        heroTitle: 'تداول بذكاء',
        heroSubtitle: 'حاسبة احترافية',
        welcome: 'مرحبا',
        readyToTrade: 'جاهز!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'زوج',
        searchPair: 'بحث... BTC',
        searchHint: 'البحث بالاسم',
        addNewPair: 'إضافة جديد',
        noPairFound: 'غير موجود',
        direction: 'اتجاه',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'آمن',
        riskModerate: 'متوسط',
        riskRisky: 'خطر',
        leverage: 'Leverage',
        levLow: 'منخفض',
        levMed: 'متوسط',
        levHigh: 'عالي',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'يجب 100%',
        add: 'إضافة',
        remove: 'حذف',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'كمية',
        riskAmount: 'مبلغ المخاطرة',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'تقييم',
        excellent: 'ممتاز!',
        good: 'جيد',
        moderate: 'متوسط',
        risky: 'خطر',
        veryRisky: 'خطر جدا!',
        save: 'حفظ',
        saving: 'جاري الحفظ...',
        savedSuccess: 'تم الحفظ!',
        viewDashboard: 'عرض التاريخ',
        continueTrading: 'متابعة',
        entryReason: 'السبب',
        selectReason: 'اختر',
        customReason: 'آخر...',
        exchange: 'Exchange',
        selectExchange: 'اختر',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'حساب الحجم',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'تتبع التداول',
        unlockFeatures: 'فتح الميزات',
        ctaDesc: 'سجل دخول',
        start: 'ابدأ',
        tradeHistory: 'التاريخ',
        quickActions: 'سريع',
        viewHistory: 'عرض',
        totalTrades: 'المجموع',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'مفتوح',
        noTrades: 'لا يوجد',
        startTrading: 'ابدأ!',
        statusOpen: 'مفتوح',
        statusWin: 'ربح',
        statusLoss: 'خسارة',
        endOrder: 'إغلاق',
        markWin: 'ربح',
        markLoss: 'خسارة',
        pleaseLogin: 'سجل دخول',
        fillAllFields: 'املأ الكل',
        invalidPair: 'XXX/USDT',
        tokenExpired: 'انتهى Token',
        serverError: 'خطأ الخادم',
        cannotSave: 'لم يحفظ',
        footer: 'أبحث عن تدريب',
        madeWith: 'صنع',
        welcomeBack: 'مرحبا!',
        createAccount: 'إنشاء حساب',
        noAccount: 'لا حساب؟',
        haveAccount: 'لديك حساب؟',
        back: 'رجوع',
        username: 'المستخدم',
        password: 'كلمة السر',
        confirmPassword: 'تأكيد',
        email: 'البريد',
        passwordMismatch: 'لا تتطابق',
        registering: 'جاري...',
        loggingIn: 'دخول...',
        registerSuccess: 'تم!',
    },

    // =====================================================================
    // 🇧🇷 Portuguese
    // =====================================================================
    pt: {
        login: 'Entrar',
        register: 'Cadastro',
        logout: 'Sair',
        dashboard: 'Histórico',
        heroTitle: 'Negocie Inteligente',
        heroSubtitle: 'Calculadora profissional',
        welcome: 'Olá',
        readyToTrade: 'Pronto!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Par',
        searchPair: 'Buscar... BTC',
        searchHint: 'Buscar por nome',
        addNewPair: 'Adicionar novo',
        noPairFound: 'Não encontrado',
        direction: 'Direção',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'Seguro',
        riskModerate: 'Moderado',
        riskRisky: 'Arriscado',
        leverage: 'Leverage',
        levLow: 'Baixo',
        levMed: 'Médio',
        levHigh: 'Alto',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'Deve ser 100%',
        add: 'Adicionar',
        remove: 'Remover',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'Quantidade',
        riskAmount: 'Valor Risco',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Avaliação',
        excellent: 'Excelente!',
        good: 'Bom',
        moderate: 'Moderado',
        risky: 'Arriscado',
        veryRisky: 'Muito Arriscado!',
        save: 'Salvar',
        saving: 'Salvando...',
        savedSuccess: 'Salvo!',
        viewDashboard: 'Ver Histórico',
        continueTrading: 'Continuar',
        entryReason: 'Motivo',
        selectReason: 'Selecionar',
        customReason: 'Outro...',
        exchange: 'Exchange',
        selectExchange: 'Selecionar',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calcule posição',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Acompanhe trades',
        unlockFeatures: 'Desbloquear',
        ctaDesc: 'Faça login',
        start: 'Começar',
        tradeHistory: 'Histórico',
        quickActions: 'Ações',
        viewHistory: 'Ver',
        totalTrades: 'Total',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'Abertos',
        noTrades: 'Sem histórico',
        startTrading: 'Começar!',
        statusOpen: 'Aberto',
        statusWin: 'Ganho',
        statusLoss: 'Perda',
        endOrder: 'Fechar',
        markWin: 'WIN',
        markLoss: 'LOSS',
        pleaseLogin: 'Faça login',
        fillAllFields: 'Preencha tudo',
        invalidPair: 'XXX/USDT',
        tokenExpired: 'Token expirado',
        serverError: 'Erro servidor',
        cannotSave: 'Não salvo',
        footer: 'Buscando estágio',
        madeWith: 'Feito com',
        welcomeBack: 'Bem-vindo!',
        createAccount: 'Criar conta',
        noAccount: 'Sem conta?',
        haveAccount: 'Tem conta?',
        back: 'Voltar',
        username: 'Usuário',
        password: 'Senha',
        confirmPassword: 'Confirmar',
        email: 'Email',
        passwordMismatch: 'Não combinam',
        registering: 'Registrando...',
        loggingIn: 'Entrando...',
        registerSuccess: 'Registrado!',
    },

    // =====================================================================
    // 🇫🇷 French
    // =====================================================================
    fr: {
        login: 'Connexion',
        register: 'Inscription',
        logout: 'Déconnexion',
        dashboard: 'Historique',
        heroTitle: 'Tradez Intelligemment',
        heroSubtitle: 'Calculatrice professionnelle',
        welcome: 'Bonjour',
        readyToTrade: 'Prêt!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Paire',
        searchPair: 'Chercher... BTC',
        searchHint: 'Chercher par nom',
        addNewPair: 'Ajouter nouveau',
        noPairFound: 'Non trouvé',
        direction: 'Direction',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'Sûr',
        riskModerate: 'Modéré',
        riskRisky: 'Risqué',
        leverage: 'Leverage',
        levLow: 'Bas',
        levMed: 'Moyen',
        levHigh: 'Haut',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'Doit être 100%',
        add: 'Ajouter',
        remove: 'Retirer',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'Quantité',
        riskAmount: 'Montant Risque',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Évaluation',
        excellent: 'Excellent!',
        good: 'Bon',
        moderate: 'Modéré',
        risky: 'Risqué',
        veryRisky: 'Très Risqué!',
        save: 'Sauver',
        saving: 'Sauvegarde...',
        savedSuccess: 'Sauvé!',
        viewDashboard: 'Voir Historique',
        continueTrading: 'Continuer',
        entryReason: 'Raison',
        selectReason: 'Sélectionner',
        customReason: 'Autre...',
        exchange: 'Exchange',
        selectExchange: 'Sélectionner',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Calculez position',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'Suivez trades',
        unlockFeatures: 'Débloquer',
        ctaDesc: 'Connectez-vous',
        start: 'Commencer',
        tradeHistory: 'Historique',
        quickActions: 'Actions',
        viewHistory: 'Voir',
        totalTrades: 'Total',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'Ouverts',
        noTrades: 'Pas d\'historique',
        startTrading: 'Commencer!',
        statusOpen: 'Ouvert',
        statusWin: 'Gagné',
        statusLoss: 'Perdu',
        endOrder: 'Fermer',
        markWin: 'WIN',
        markLoss: 'LOSS',
        pleaseLogin: 'Connectez-vous',
        fillAllFields: 'Remplir tout',
        invalidPair: 'XXX/USDT',
        tokenExpired: 'Token expiré',
        serverError: 'Erreur serveur',
        cannotSave: 'Non sauvé',
        footer: 'Recherche stage',
        madeWith: 'Fait avec',
        welcomeBack: 'Bienvenue!',
        createAccount: 'Créer compte',
        noAccount: 'Pas de compte?',
        haveAccount: 'Déjà un compte?',
        back: 'Retour',
        username: 'Utilisateur',
        password: 'Mot de passe',
        confirmPassword: 'Confirmer',
        email: 'Email',
        passwordMismatch: 'Non identiques',
        registering: 'Inscription...',
        loggingIn: 'Connexion...',
        registerSuccess: 'Inscrit!',
    },

    // =====================================================================
    // 🇷🇺 Russian
    // =====================================================================
    ru: {
        login: 'Вход',
        register: 'Регистрация',
        logout: 'Выход',
        dashboard: 'История',
        heroTitle: 'Торгуй Умнее',
        heroSubtitle: 'Профессиональный калькулятор',
        welcome: 'Привет',
        readyToTrade: 'Готов!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'Пара',
        searchPair: 'Поиск... BTC',
        searchHint: 'Поиск по названию',
        addNewPair: 'Добавить новый',
        noPairFound: 'Не найдено',
        direction: 'Направление',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: 'Безопасно',
        riskModerate: 'Умеренно',
        riskRisky: 'Рискованно',
        leverage: 'Leverage',
        levLow: 'Низкий',
        levMed: 'Средний',
        levHigh: 'Высокий',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: 'Должно быть 100%',
        add: 'Добавить',
        remove: 'Удалить',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: 'Количество',
        riskAmount: 'Сумма риска',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: 'Оценка',
        excellent: 'Отлично!',
        good: 'Хорошо',
        moderate: 'Средне',
        risky: 'Рискованно',
        veryRisky: 'Очень рискованно!',
        save: 'Сохранить',
        saving: 'Сохранение...',
        savedSuccess: 'Сохранено!',
        viewDashboard: 'Смотреть историю',
        continueTrading: 'Продолжить',
        entryReason: 'Причина',
        selectReason: 'Выбрать',
        customReason: 'Другое...',
        exchange: 'Exchange',
        selectExchange: 'Выбрать',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: 'Расчет позиции',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: 'История сделок',
        unlockFeatures: 'Разблокировать',
        ctaDesc: 'Войдите',
        start: 'Начать',
        tradeHistory: 'История',
        quickActions: 'Действия',
        viewHistory: 'Смотреть',
        totalTrades: 'Всего',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: 'Открытые',
        noTrades: 'Нет истории',
        startTrading: 'Начать!',
        statusOpen: 'Открыто',
        statusWin: 'Прибыль',
        statusLoss: 'Убыток',
        endOrder: 'Закрыть',
        markWin: 'Прибыль',
        markLoss: 'Убыток',
        pleaseLogin: 'Войдите',
        fillAllFields: 'Заполните все',
        invalidPair: 'XXX/USDT',
        tokenExpired: 'Token истек',
        serverError: 'Ошибка сервера',
        cannotSave: 'Не сохранено',
        footer: 'Ищу стажировку',
        madeWith: 'Сделано',
        welcomeBack: 'Добро пожаловать!',
        createAccount: 'Создать аккаунт',
        noAccount: 'Нет аккаунта?',
        haveAccount: 'Есть аккаунт?',
        back: 'Назад',
        username: 'Пользователь',
        password: 'Пароль',
        confirmPassword: 'Подтвердить',
        email: 'Email',
        passwordMismatch: 'Не совпадают',
        registering: 'Регистрация...',
        loggingIn: 'Вход...',
        registerSuccess: 'Зарегистрирован!',
    },

    // =====================================================================
    // 🇯🇵 Japanese
    // =====================================================================
    ja: {
        login: 'ログイン',
        register: '登録',
        logout: 'ログアウト',
        dashboard: '履歴',
        heroTitle: 'スマートに取引',
        heroSubtitle: 'プロ用計算機',
        welcome: 'こんにちは',
        readyToTrade: '準備完了!',
        positionCalc: 'Position Calculator',
        calcDesc: 'Multi-TP/SL + AI Score',
        tradingPair: 'ペア',
        searchPair: '検索... BTC',
        searchHint: '名前で検索',
        addNewPair: '新規追加',
        noPairFound: '見つかりません',
        direction: '方向',
        portfolio: 'Portfolio',
        entryPrice: 'Entry Price',
        risk: 'Risk',
        riskSafe: '安全',
        riskModerate: '中程度',
        riskRisky: 'リスク',
        leverage: 'Leverage',
        levLow: '低',
        levMed: '中',
        levHigh: '高',
        stopLoss: 'Stop Loss',
        takeProfit: 'Take Profit',
        mustBe100: '100%必須',
        add: '追加',
        remove: '削除',
        positionSize: 'Position Size',
        requiredMargin: 'Required Margin',
        quantity: '数量',
        riskAmount: 'リスク額',
        maxWin: 'Max Win',
        maxLoss: 'Max Loss',
        rrRatio: 'R:R Ratio',
        fee: 'Fee',
        aiScore: 'AI Trade Score',
        aiScoreDesc: '評価',
        excellent: '素晴らしい!',
        good: '良い',
        moderate: '普通',
        risky: 'リスク',
        veryRisky: '高リスク!',
        save: '保存',
        saving: '保存中...',
        savedSuccess: '保存完了!',
        viewDashboard: '履歴を見る',
        continueTrading: '続ける',
        entryReason: '理由',
        selectReason: '選択',
        customReason: 'その他...',
        exchange: 'Exchange',
        selectExchange: '選択',
        riskMgmt: 'Risk Management',
        riskMgmtDesc: '最適サイズ計算',
        tradeJournal: 'Trade Journal',
        tradeJournalDesc: '取引履歴追跡',
        unlockFeatures: 'ロック解除',
        ctaDesc: 'ログインして',
        start: '始める',
        tradeHistory: '履歴',
        quickActions: 'クイック',
        viewHistory: '見る',
        totalTrades: '合計',
        winRate: 'Win Rate',
        totalPnl: 'Total PnL',
        openTrades: '保有中',
        noTrades: '履歴なし',
        startTrading: '始める!',
        statusOpen: '保有中',
        statusWin: '利益',
        statusLoss: '損失',
        endOrder: '決済',
        markWin: '利益',
        markLoss: '損失',
        pleaseLogin: 'ログインして',
        fillAllFields: '全て記入',
        invalidPair: 'XXX/USDT形式',
        tokenExpired: 'Token期限切れ',
        serverError: 'サーバーエラー',
        cannotSave: '保存失敗',
        footer: 'インターン探し中',
        madeWith: '作成',
        welcomeBack: 'おかえり!',
        createAccount: 'アカウント作成',
        noAccount: 'アカウントなし?',
        haveAccount: 'アカウントある?',
        back: '戻る',
        username: 'ユーザー名',
        password: 'パスワード',
        confirmPassword: '確認',
        email: 'メール',
        passwordMismatch: '不一致',
        registering: '登録中...',
        loggingIn: 'ログイン中...',
        registerSuccess: '登録完了!',
    },
};

// ===================================================================
// Context Type Definition
// ===================================================================
interface LanguageContextType {
    lang: LangCode;
    setLang: (lang: LangCode) => void;
    t: (key: string) => string;
    flag: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ===================================================================
// Provider Component - ครอบทั้งแอปเพื่อให้ทุกที่เข้าถึงภาษาได้
// ===================================================================
export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLangState] = useState<LangCode>('th');

    /**
     * โหลดภาษาจาก localStorage ตอนเริ่มต้น
     * ถ้าผู้ใช้เคยเลือกภาษาไว้ จะจำไว้
     */
    useEffect(() => {
        const saved = localStorage.getItem('lang') as LangCode;
        if (saved && languages.some(l => l.code === saved)) {
            setLangState(saved);
        }
    }, []);

    /**
     * เปลี่ยนภาษาและบันทึกลง localStorage
     */
    const setLang = (newLang: LangCode) => {
        setLangState(newLang);
        localStorage.setItem('lang', newLang);
    };

    /**
     * ฟังก์ชันแปลภาษา (Translation Function)
     * @param key - รหัสข้อความ เช่น 'login', 'save'
     * @returns ข้อความในภาษาที่เลือก
     * 
     * Logic:
     * 1. หาใน dictionary ของภาษาปัจจุบัน
     * 2. ถ้าไม่มี ใช้ภาษาอังกฤษแทน (fallback)
     * 3. ถ้าไม่มีเลย แสดง key เลย (สำหรับ debug)
     */
    const t = (key: string): string => {
        return dictionary[lang][key] || dictionary['en'][key] || key;
    };

    // ธงชาติปัจจุบัน
    const flag = languages.find(l => l.code === lang)?.flag || '🇹🇭';

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, flag }}>
            {children}
        </LanguageContext.Provider>
    );
}

// ===================================================================
// Custom Hook - ใช้ในทุก Component ที่ต้องการแปลภาษา
// ===================================================================
export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
